# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:5001  # Add this environment variable
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./:/app
      - /app/__pycache__
      - /app/app/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app/app.py
    networks:
      - app-network
    command: python ./app/app.py

networks:
  app-network:
    driver: bridge