export const FILTER_OPTIONS = {
    primarySites: [
      "accessory sinuses",
    "adrenal gland",
    "anus and anal canal",
    "base of tongue",
    "bladder",
    "bones, joints and articular cartilage of limbs",
    "bones, joints and articular cartilage of other and unspecified sites",
    "brain",
    "breast",
    "bronchus and lung",
    "cervix uteri",
    "colon",
    "connective, subcutaneous and other soft tissues",
    "corpus uteri",
    "esophagus",
    "eye and adnexa",
    "floor of mouth",
    "gallbladder",
    "gum",
    "heart, mediastinum, and pleura",
    "hematopoietic and reticuloendothelial systems",
    "hypopharynx",
    "kidney",
    "larynx",
    "lip",
    "liver and intrahepatic bile ducts",
    "lymph nodes",
    "meninges",
    "nasal cavity and middle ear",
    "nasopharynx",
    "not reported",
    "oropharynx",
    "other and ill-defined digestive organs",
    "other and ill-defined sites",
    "other and ill-defined sites in lip, oral cavity and pharynx",
    "other and ill-defined sites within respiratory system and intrathoracic organs",
    "other and unspecified female genital organs",
    "other and unspecified major salivary glands",
    "other and unspecified male genital organs",
    "other and unspecified parts of biliary tract",
    "other and unspecified parts of mouth",
    "other and unspecified parts of tongue",
    "other and unspecified urinary organs",
    "other endocrine glands and related structures",
    "ovary",
    "palate",
    "pancreas",
    "parotid gland",
    "penis",
    "peripheral nerves and autonomic nervous system",
    "prostate gland",
    "rectosigmoid junction",
    "rectum",
    "renal pelvis",
    "retroperitoneum and peritoneum",
    "skin",
    "small intestine",
    "spinal cord, cranial nerves, and other parts of central nervous system",
    "stomach",
    "testis",
    "thymus",
    "thyroid gland",
    "tonsil",
    "trachea",
    "unknown",
    "ureter",
    "uterus, nos",
    "vagina",
    "vulva"
    ],
    
    expStrategies: [
        "ATAC-Seq",
        "Diagnostic Slide",
        "Expression Array",
        "Genotyping Array",
        "Methylation Array",
        "miRNA-Seq",
        "Reverse Phase Protein Array",
        "RNA-Seq",
        "scRNA-Seq",
        "Targeted Sequencing",
        "Tissue Slide",
        "WGS",
        "WXS"
    ],
    
    diseaseTypes: [
     "acinar cell neoplasms",
    "acute lymphoblastic leukemia",
    "adenomas and adenocarcinomas",
    "adnexal and skin appendage neoplasms",
    "basal cell neoplasms",
    "blood vessel tumors",
    "chronic myeloproliferative disorders",
    "complex epithelial neoplasms",
    "complex mixed and stromal neoplasms",
    "cystic, mucinous and serous neoplasms",
    "ductal and lobular neoplasms",
    "epithelial neoplasms, nos",
    "fibroepithelial neoplasms",
    "fibromatous neoplasms",
    "germ cell neoplasms",
    "gliomas",
    "leukemias, nos",
    "lipomatous neoplasms",
    "lymphoid leukemias",
    "mature b-cell lymphomas",
    "mature t- and nk-cell lymphomas",
    "meningiomas",
    "mesothelial neoplasms",
    "miscellaneous bone tumors",
    "miscellaneous tumors",
    "mucoepidermoid neoplasms",
    "myelodysplastic syndromes",
    "myeloid leukemias",
    "myomatous neoplasms",
    "neoplasms, nos",
    "nerve sheath tumors",
    "neuroepitheliomatous neoplasms",
    "nevi and melanomas",
    "not applicable",
    "not reported",
    "osseous and chondromatous neoplasms",
    "paragangliomas and glomus tumors",
    "plasma cell tumors",
    "soft tissue tumors and sarcomas, nos",
    "specialized gonadal neoplasms",
    "squamous cell neoplasms",
    "synovial-like neoplasms",
    "thymic epithelial neoplasms",
    "transitional cell papillomas and carcinomas",
    "unknown"
    ],
    
    dataCategories: [
        "biospecimen",
        "clinical",
        "combined nucleotide variation",
        "copy number variation",
        "dna methylation",
        "proteome profiling",
        "sequencing reads",
        "simple nucleotide variation",
        "somatic structural variation",
        "structural variation",
        "transcriptome profiling"
    ]
  } as const;
  export const getFilterOptions = {
    primarySites: () => [...FILTER_OPTIONS.primarySites] as string[],
    expStrategies: () => [...FILTER_OPTIONS.expStrategies] as string[],
    dataCategories: () => [...FILTER_OPTIONS.dataCategories] as string[],
    diseaseTypes: () => [...FILTER_OPTIONS.diseaseTypes] as string[]
  };